apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: dashboard
spec:
  selector:
    app: nginx-exporter
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
  type: ClusterIP
