version: '3.9'
services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - lol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: hello 
      MONGO_INITDB_ROOT_PASSWORD: secret

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard
    restart: always
    ports:
      - "5000:5000" 
    depends_on:
      - db
    environment:
      #DB_NAME: test 
      DB_USERNAME: hello 
      DB_PASS: secret 
      DB_HOST: "db"
      DB_PORT: 27017

volumes:
  lol:
