version: '3.9'
services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - lol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: hello 
      MONGO_INITDB_ROOT_PASSWORD: secret

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard
    restart: always
    ports:
      - "5000:5000" 
    depends_on:
      - db
    environment:
      DB_USERNAME: hello 
      DB_PASS: secret 
      DB_HOST: "db"
      DB_PORT: 27017

  mongodb-exporter:
    image: percona/mongodb_exporter:0.20
    container_name: mongodb-exporter
    environment:
      - MONGODB_USER=hello
      - MONGODB_PASSWORD=secret
    ports:
      - "9216:9216"
    command: --mongodb.uri=mongodb://db:27017
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/ # Mount the nginx.conf file
    depends_on:
      - dashboard

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    restart: always
    ports:
      - "9113:9113"
    command: -nginx.scrape-uri=http://nginx:80/metrics
    depends_on:
      - nginx

volumes:
  lol: